### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by iamrk-in** [danielgross/whatsapp-gpt#30]
Traceback (most recent call last):
  File "server.py", line 5, in <module>
    import flask
ModuleNotFoundError: No module named 'flask'

**Comment by adalbertobrant** [comment]
> Traceback (most recent call last): File "server.py", line 5, in import flask ModuleNotFoundError: No module named 'flask'

pip install flask

**Comment by sonuu26** [comment]
still not working

**Comment by sonuu26** [comment]
still not working
![ss](https://user-images.githubusercontent.com/77972032/210944112-02e8914d-ea1e-4abe-a1e0-fc20f7e56bdf.png)

**Comment by B4sicallyF0x** [comment]
nice lenovo pc hahah

**Comment by kazzastic** [comment]
maybe you run your python scripts from some other environment, if so then you need to go and install Flask in that particular environment. If you could show where your python scripts run from then maybe someone could help more.
